server:
  port: 8080

guacamole:
  guacd:
    hostname: localhost
    port: 4822
    ssl: false

  # Authentication extensions (enable via Maven dependency + set to true)
  auth:
    header:
      enabled: true
    duo:
      enabled: false
    json:
      enabled: true
    ldap:
      enabled: true
      ldap-hostname: ldap.forumsys.com
      ldap-port: 389
      ldap-user-base-dn: dc=example,dc=com
      ldap-username-attribute: uid
    totp:
      enabled: false
    radius:
      enabled: true
    quickconnect:
      enabled: true
    mysql:
      enabled: false
    postgresql:
      enabled: true
    sqlserver:
      enabled: false
    sso-cas:
      enabled: false
    sso-openid:
      enabled: false
    sso-saml:
      enabled: false

  vault:
    ksm:
      enabled: false

# History configuration 录像名配置为：${HISTORY_UUID}
  history:
    enabled: true
    recording-search-path: /tmp/guacamole/recordings

spring:
  datasource:
    url: jdbc:postgresql://192.168.5.188:5432/guacamole
    username: guacamole
    password: guacamole
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: "off"
  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    org.apache.guacamole.history: info